import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/SidebarMenu";
import Footer from "@/components/Footer";
import { Providers } from "@/redux/provider/providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen flex flex-col justify-between`}
      >
        <Providers>
          <div className="flex flex-1">
            <Sidebar />
            <div className="flex-1">{children}</div>
          </div>
          <Footer />
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
